import * as Automerge from "@automerge/automerge";
import type { BlockChange, BlockState, DocBlock, DocsCodeState, JournalEvent } from "./types.js";
export type CrdtState = Automerge.Doc<DocsCodeState>;
export declare function stateDir(root: string): string;
export declare function statePath(root: string): string;
export declare function automergePath(root: string): string;
export declare function plansDir(root: string): string;
export declare function createBlockId(): string;
export declare function blockToState(block: DocBlock, blockId?: string): BlockState;
export declare function loadCrdtState(root: string, docsDir?: string): Promise<CrdtState>;
export declare function saveCrdtState(root: string, doc: CrdtState): Promise<void>;
export declare function loadState(root: string, docsDir?: string): Promise<DocsCodeState>;
export declare function saveState(root: string, state: DocsCodeState): Promise<void>;
export declare function observeBlocks(doc: CrdtState, blocks: DocBlock[], eventType: JournalEvent["type"]): CrdtState;
export declare function baselineState(root: string, blocks: DocBlock[], docsDir?: string): Promise<DocsCodeState>;
export declare function markImplemented(root: string, blocks: DocBlock[], docsDir?: string): Promise<DocsCodeState>;
export declare function markChangesImplemented(root: string, changes: BlockChange[], docsDir?: string): Promise<DocsCodeState>;
