/* Agent protocol and README template generation for spec-coding. */
import { MARKDOWN_METADATA_UPDATED, MARKDOWN_METADATA_VERSION, withMarkdownMetadata } from "./metadata.js";

function agentProtocolMd(fileName: "AGENTS.md" | "CLAUDE.md", projectName: string): string {
  const name = fileName === "AGENTS.md" ? "agents" : "claude";
  return withMarkdownMetadata({
    name,
    version: MARKDOWN_METADATA_VERSION,
    title: fileName,
    type: "agent-protocol",
    source: "spec-coding-mcp",
    description: `Startup protocol for AI coding agents working on ${projectName}.`,
    category: "workflow",
    triggers: ["startup", "coding-agent", "spec-context", "guidance"],
    appliesTo: ["agents", "model-startup", "workflow-routing"],
    updated: MARKDOWN_METADATA_UPDATED
  }, [
    `# ${fileName}`,
    "",
    `Project: ${projectName}`,
    "",
    "## 项目约定（所有人适用）",
    "",
    "改动小而聚焦，不做无关重构 / 不猜测业务规则 / 不覆盖他人修改 / 提交前验证",
    "",
    "## Spec Coding MCP（可选增强）",
    "",
    "",
    "本项目支持 spec-coding-mcp 工具。查看可用工具列表中是否有 spec_context。",
    "",
    "### 如果你有 spec_context 工具",
    "1. 先调 spec_context → 按 TODO 执行 → checkpoint → 验证 → done",
    "2. UI/UX 用 ui-ux-pro-max skill",
    "3. 需要指导时调 spec_guidance_read",
    "",
    "## Guidance 索引（仅 MCP 用户）",
    "",
    "- `engineering`：engineering, code style, architecture, and business confirmation rules.",
    "- `ui-ux`：fact-first, context-sensitive UI/UX design principles; default UI/UX skill is `ui-ux-pro-max`.",
    "- `spec-writing`：spec workflow, execution checklist, progress records, done archives, and behavior records.",
    "- `git-commit`：safe verification, staging, commit message, and final report workflow.",
    "- `pr-submit`：PR template discovery, branch push, PR body, creation, and fallback workflow.",
    "- `quality-review`：implementation self-review for code quality, tests, architecture, UI/UX states, and delivery risk.",
    "",
    "### 如果你没有 spec_context 工具 / 跳过本节，按常规开发流程工作",
    "`spec_skills_search` searches skills.sh through the official skills CLI. `spec_skills_install` uses the bundled official skills CLI, with `npx skills add` fallback, defaulting to global Codex installation of `ui-ux-pro-max` from `https://github.com/nextlevelbuilder/ui-ux-pro-max-skill`.",
    "",
    "## Hard Stop",
    "",
    "### 常见错误 / 不调 spec_context 就写代码 / 跳过验证直接 done / 监听型 TODO 自己标完成",
    "",
    "## Boundaries（所有人适用）",
    "",
    "- Do not guess business rules.",
    "- Do not use stale conversation context over selected specs or open TODOs.",
    "- Do not overwrite user edits or make unrelated reshuffles.",
    "- Keep changes small, focused, and verified."
  ]);
}


/** The standalone Spec Coding MCP section that can be safely appended to an existing AGENTS.md / CLAUDE.md
 * without overwriting the colleague's own content. */
export function specCodingMcpAppendix(): string {
  return [
    "",
    "## Spec Coding MCP（可选增强）",
    "",
    "本项目支持 spec-coding-mcp 工具提供增强开发流程。",
    "",
    "**检测方法**：查看可用工具列表中是否有 `spec_context`。",
    "",
    "### 如果你有 `spec_context` 工具",
    "",
    "1. 写任何代码前，先调用 `spec_context` 获取当前任务上下文。",
    "2. 只执行 spec/TODO 中列出的任务，不从对话历史推导。",
    "3. 按清单自上而下执行 → `spec_checkpoint` 记录进度 → 验证 → `spec_done` 归档。",
    "4. UI/UX 任务使用 `ui-ux-pro-max` skill。",
    "5. 需要原则指导时调用 `spec_guidance_read`。",
    "",
    "常见错误：不调 spec_context 就写代码 / 跳过验证直接 done / 监听型 TODO 自己标完成。",
    "",
    "### 如果你没有 `spec_context` 工具",
    "",
    "跳过本节。按项目常规开发流程工作：读需求 → 写代码 → 测试 → 提交。",
    "不要尝试调用 spec_context、spec_checkpoint、spec_done 等不存在的工具。",
    "",
    "## Guidance 索引（仅 MCP 用户）",
    "",
    "需要原则时调用 `spec_guidance_read`：",
    "",
    "| Name | 用途 | 何时读 |",
    "| --- | --- | --- |",
    "| `engineering` | 工程规范、业务确认 | 实现/重构 |",
    "| `ui-ux` | UI/UX skill 路由 | 前端/页面 |",
    "| `spec-writing` | spec 工作流、验证器 | 创建/执行 spec |",
    "| `git-commit` | 安全提交流程 | 用户要求 commit |",
    "| `pr-submit` | PR 创建流程 | 用户要求 PR |",
    "| `quality-review` | 质量自检清单 | done/commit/PR 前 |",
    "",
    "按需读取，不要提前加载大量 guidance 到上下文。"
  ].join("\n");
}
export function agentsMd(projectName: string): string {
  return agentProtocolMd("AGENTS.md", projectName);
}

export function claudeMd(projectName: string): string {
  return agentProtocolMd("CLAUDE.md", projectName);
}

export function specsReadme(projectName: string): string {
  return withMarkdownMetadata({
    name: "specs-readme",
    version: MARKDOWN_METADATA_VERSION,
    title: `${projectName} Specs`,
    type: "specs-readme",
    status: "reference",
    source: "spec-coding-mcp",
    description: `Spec workflow index and conventions for ${projectName}.`,
    category: "workflow",
    triggers: ["specs", "workflow", "todo", "done", "guidance"],
    appliesTo: ["specs-directory", "workflow-docs", "agent-reference"],
    updated: MARKDOWN_METADATA_UPDATED
  }, [
    `# ${projectName} Specs`,
    "",
    "本目录用于 spec coding：先写清楚规格，再让 AI 按规格修改代码和测试。",
    "",
    "## 前置要求",
    "",
    "任何代码或文档变更之前，必须先调用 `spec_context` 并读取输出。",
    "如果当前没有 `spec_context` 结果，就不要直接开始实现。",
    "",
    "## 工作流",
    "",
    "1. 先调用 `spec_bootstrap` 建立项目入口：新项目生成起步 active spec，旧项目生成 AI 源码审查任务。",
    "2. 再调用 `spec_context`，确认当前任务的 spec、TODO 和工程约束。",
    "3. AI 必须阅读 `review/*.md` 列出的源码和测试，再把真实行为总结成业务规格。",
    "4. 小任务放在 `todo/`；功能开发放在 `active/`。",
    "5. Codex 按 spec 和未勾选执行清单修改代码和测试。",
    "6. 阶段完成后调用 `spec_checkpoint` 记录进度、验证和执行记录。",
    "7. 验证通过且最终行为契约已记录后，才能调用 `spec_done`。",
    "",
    "## 状态",
    "",
    "- `source-review/needs-ai-summary`：静态源码线索生成的 AI 审查任务，不代表业务事实，必须阅读源码后补全。",
    "- `draft`：用户正在描述需求，尚未实现。",
    "- `active`：准备实现或正在实现。",
    "- `todo`：轻量执行清单，AI 应按未勾选项顺序执行。",
    "- `done`：代码和测试已按该 spec 完成。",
    "",
    "## 目录",
    "",
    "- `review/`：指导 AI 阅读源码并总结真实行为的待审查任务。",
    "- `active/YYYY-MM-DD/NNN-readable-name.md`：当前要实现的 specs，按日期和当天顺序归档。",
    "- `todo/YYYY-MM-DD/NNN-readable-name.md`：可执行清单，适合拆分小任务或补充实现步骤。",
    "- `done/YYYY-MM-DD/NNN-readable-name.md`：已经完成的 specs，必须保留来自代码和测试验证的最终行为契约。",
    "- `guidance/*.md`：可编辑的指导性提示词，供 `spec_guidance_list` 和 `spec_guidance_read` 按需读取。",
    "",
    "## 指导性提示词",
    "",
    "`spec_guidance_list` 会列出内置 guidance 名称、版本、分类、描述、触发词、适用对象和对应 Markdown 路径；`spec_guidance_read` 会读取某一份提示词。",
    "默认 guidance 文件顶部包含类似 SKILL.md 的 YAML 元信息：`name`、`version`、`title`、`description`、`category`、`triggers`、`appliesTo` 和 `updated`，方便工具和模型检索；普通 README 和 VitePress docs 页面不默认加入这套元信息。",
    "这些提示词只用于在模型忘记工程、UI/UX、spec 写作、Git 提交、PR 工作流或质量审查原则时按需提醒，不替代当前 spec、TODO、用户要求或代码事实。",
    "`spec_context` 只显示 guidance 索引和必要执行护栏，不展开完整原则正文；需要细节时再按 name 读取 guidance。",
    "用户可以直接编辑 `guidance/*.md`；目录缺失、为空或缺少默认文件时，工具会补齐内置默认 Markdown，已有文件不会被覆盖。",
    "",
    "## Skills",
    "",
    "- `spec_skills_search` 通过官方 skills CLI 搜索 skills.sh，适合复杂任务前寻找专门能力。",
    "- `spec_skills_install` 优先使用随包安装的 official skills CLI，必要时回退 `npx skills add`；默认安装 `https://github.com/nextlevelbuilder/ui-ux-pro-max-skill` 中的 `ui-ux-pro-max` 到 Codex 全局 skills 目录。",
    "- UI/UX 任务默认优先使用 `ui-ux-pro-max` skill，但仍必须服从项目事实、用户语境和当前 `ui-ux` guidance。",
    "",
    "## Markdown 正文结构",
    "",
    "- YAML front matter 承载 `status`、`source`、`type` 等机器字段；新生成正文不再重复 `## Meta`。",
    "- 常用正文标题包括：`任务说明`、`执行清单`、`执行协议`、`执行记录`、`进度记录`、`归档记录`、`最终行为契约`。",
    "- 工具仍兼容旧文件里的 `## Meta`、`- status:` 和 `- source:`。",
    "",
    "## 命名要求",
    "",
    "- 文件名使用当天递增序号和可读业务名，避免 `todo-9.md` 这类无法审查的名称。",
    "- `done/` 只记录实际代码行为、测试结果或用户确认事实；禁止把猜测写成最终行为。"
  ]);
}
