/* User-authored spec templates and source-derived review spec templates. */
import { guidancePointerSection, list, workflowGuardSection } from "./markdown.js";
import { MARKDOWN_METADATA_UPDATED, MARKDOWN_METADATA_VERSION, withMarkdownMetadata } from "./metadata.js";
import type { SourceScanSummary, SourceSpecCandidate } from "../spec/types.js";

export function specTemplate(kind: "feature" | "bugfix" | "removal"): string {
  const title = kind === "feature" ? "新增功能" : kind === "bugfix" ? "问题修复" : "移除功能";
  return withMarkdownMetadata({
    name: `${kind}-spec-template`,
    version: MARKDOWN_METADATA_VERSION,
    title,
    type: "spec-template",
    status: "draft",
    source: "user-authored",
    description: `Editable ${kind} spec template for behavior-driven implementation.`,
    category: "spec-template",
    triggers: [kind, "spec", "implementation", "verification"],
    appliesTo: ["active-specs", "templates", "behavior-records"],
    updated: MARKDOWN_METADATA_UPDATED
  }, [
    `# ${title}`,
    "",
    "## 目标结果",
    "",
    "- 待描述。",
    "",
    "## 事实依据",
    "",
    "- 项目真实定位：待确认；不明确时先向用户确认或搜索验证。",
    "- 真实对象：列出首屏/核心流程必须出现的 repo、截图、demo、项目矩阵、核心交互、组件或数据。",
    "- 事实来源：列出可用于文案和结构的用户输入、README、源码、配置、公开链接或明确确认。",
    "- 禁止编造：指标、客户、性能数据、邮箱、融资、商业定位、社区规模和路线图承诺都必须有来源。",
    "- CTA：只使用真实下一步；官网 CTA 必须匹配企业官网、产品官网、个人作品集、开源组织或文档站的实际类型。",
    "",
    "## 影响范围",
    "",
    "- 后端/API：待确认",
    "- 前端/客户端：待确认",
    "- 数据/迁移：待确认",
    "- 测试：待确认",
    "",
    "## 行为约定",
    "",
    "| 场景 | 条件 | 预期结果 |",
    "|---|---|---|",
    "| 正常 | 待补充 | 待补充 |",
    "| 失败 | 待补充 | 待补充 |",
    "",
    "## 实现计划",
    "",
    "- 目标能力：待补充要新增、修改或移除的业务能力。",
    "- 阅读入口：列出已读取或必须读取的源码、测试、配置和文档。",
    "- 改动文件：列出计划修改的文件和每个文件承担的职责。",
    "- 数据流：描述触发入口、输入与前置状态、执行步骤、输出结果、副作用和持久化边界。",
    "- 分支处理：列出正常、失败、边界、权限、状态和异常分支。",
    "- 默认值/配置：列出默认参数、配置来源、覆盖规则和环境差异。",
    "- 验证命令：列出计划运行的测试、构建、lint 或人工验证命令。",
    "- 待确认问题：列出业务规则不明确、影响面大或高风险的点；未确认前不要实现。",
    "",
    "## UI/交互 Skill 路由",
    "",
    "- 仅当前端、页面、组件或交互受影响时填写。",
    "- UI/UX 工作不要在 spec 中展开本地设计原则或 checklist；读取 `ui-ux` guidance 后使用指定的 `ui-ux-pro-max` skill。",
    "- 如果 `ui-ux-pro-max` 未安装，先调用 `spec_skills_install`；需要预览命令时使用 `dryRun: true`。",
    "- 如果需要其他专项 UI/UX skill，先调用 `spec_skills_search` 搜索 skills.sh，再按任务需要安装。",
    "- 记录实际使用的 skill、安装或 dry-run 结果，以及该 skill 产出的关键设计/验收建议。",
    "",
    "## 执行记录",
    "",
    "- 记录来源：只能记录已阅读代码、已修改代码、测试结果或用户确认的事实。",
    "- 功能全过程：按功能点记录触发入口、输入与前置状态、执行步骤、输出结果和副作用。",
    "- 分支条件：完成后补充实际存在的正常、失败、边界、权限和状态分支，不只写一句结果。",
    "- 默认参数行为：完成后补充源码里的默认值、配置来源、覆盖规则以及未传参数时的完整流程。",
    "- 边界处理结果：完成后补充异常、空值、权限、状态等输入如何进入分支、在哪里返回、是否产生副作用。",
    "- 验证结果：完成后记录验证命令、覆盖的流程分支和关联文件。",
    "- 禁止事项：不要把猜测、常识或“看起来合理”的行为写成事实。",
    "",
    "## 完成标准",
    "",
    "- 待补充可验证结果。",
    "",
    ...workflowGuardSection(),
    "",
    ...guidancePointerSection(),
    "",
    "## 执行清单",
    "",
    "- [ ] 按本 spec 定位相关代码。",
    "- [ ] 更新实现和测试。",
    "- [ ] 运行验证并记录结果。",
    "",
    "## 代码线索",
    "",
    "- 待补充相关文件、函数、路由、组件或测试。"
  ]);
}

export function sourceInventory(summary: SourceScanSummary, generatedAt: string): string {
  const section = (title: string, items: string[]) => [`## ${title}`, "", ...list(items), ""].join("\n");
  return withMarkdownMetadata({
    name: "source-inventory",
    version: MARKDOWN_METADATA_VERSION,
    title: "源码审查线索清单",
    type: "source-inventory",
    status: "review",
    source: "static-source-hints",
    description: "Static source scan inventory for AI review routing; not a business fact source.",
    category: "review",
    triggers: ["source-review", "inventory", "bootstrap", "existing-project"],
    appliesTo: ["review-specs", "source-scan", "code-reading"],
    updated: MARKDOWN_METADATA_UPDATED
  }, [
    "# 源码审查线索清单",
    "",
    `生成时间：${generatedAt}`,
    "",
    `扫描源码和配置文件 ${summary.totalFiles} 个。以下只是静态启发式线索，用于帮助 AI 选择阅读入口，不代表业务事实或最终 spec。`,
    "",
    section("Manifest", summary.manifests),
    section("API 文件", summary.apiFiles),
    section("UI 文件", summary.uiFiles),
    section("数据文件", summary.dataFiles),
    section("测试文件", summary.testFiles),
    section("路由线索", summary.routeHints),
    section("组件线索", summary.componentHints),
    section("模型线索", summary.modelHints)
  ]);
}

export function reviewIndex(specsDir: string, candidates: SourceSpecCandidate[]): string {
  return withMarkdownMetadata({
    name: "review-index",
    version: MARKDOWN_METADATA_VERSION,
    title: "AI 源码审查任务索引",
    type: "review-index",
    status: "review",
    source: "static-source-hints",
    description: "Index of source-derived review specs for AI code reading tasks.",
    category: "review",
    triggers: ["source-review", "review-index", "bootstrap", "existing-project"],
    appliesTo: ["review-specs", "source-review", "workflow-routing"],
    updated: MARKDOWN_METADATA_UPDATED
  }, [
    "# AI 源码审查任务索引",
    "",
    "| Spec | 文件 | 状态 | 来源 |",
    "|---|---|---|---|",
    ...(candidates.length
      ? candidates.map((item) => `| ${item.title} | \`${specsDir}/review/${item.domain}-${item.name}.md\` | source-review/needs-ai-summary | 静态线索，待 AI 阅读源码 |`)
      : ["| 待补充 | 待补充 | 待审查 | 静态线索，待 AI 阅读源码 |"])
  ]);
}

export function sourceReviewSpec(projectName: string, input: SourceSpecCandidate): string {
  return withMarkdownMetadata({
    name: `${input.domain}-${input.name}`,
    version: MARKDOWN_METADATA_VERSION,
    title: input.title,
    type: "source-review-spec",
    status: "source-review/needs-ai-summary",
    source: "static-source-hints",
    description: `Source-derived review task for ${projectName}; AI must read real code before writing business facts.`,
    category: "review",
    triggers: ["source-review", input.domain, "code-reading", "behavior-summary"],
    appliesTo: ["review-specs", "source-code", "tests", "behavior-records"],
    updated: MARKDOWN_METADATA_UPDATED
  }, [
    `# ${input.title}`,
    "",
    "## 审查说明",
    "",
    `本文件由 MCP 基于 \`${projectName}\` 的源码路径、命名、路由、导出和测试线索生成。它不是业务结论，只是交给 AI 阅读源码的任务单。`,
    "",
    "- 禁止把下面的静态线索当成业务事实。",
    "- AI 必须打开并阅读相关源码、测试和配置后，再填写业务目标、行为约定和完成标准。",
    "- 金额、状态机、并发、权限等规则来源不明时，必须向用户确认。",
    "",
    "## 优先阅读入口",
    "",
    ...list(input.evidence),
    "",
    "## 路由/接口搜索线索",
    "",
    ...list(input.routes, "未识别到明显路由"),
    "",
    "## UI/客户端搜索线索",
    "",
    ...list(input.components, "未识别到明显组件"),
    "",
    "## 数据模型搜索线索",
    "",
    ...list(input.models, "未识别到明显模型"),
    "",
    "## 测试搜索线索",
    "",
    ...list(input.tests, "未识别到相关测试"),
    "",
    "## 阅读任务",
    "",
    "- 读取优先入口、相关导入导出、调用方和测试，确认真实业务目标。",
    "- 按功能点总结完整运行过程：触发入口、输入来源、处理步骤、输出结果、副作用、失败分支、默认参数、边界条件、权限和数据约束。",
    "- 标明哪些行为来自源码证据，哪些规则仍需用户确认。",
    "- 若要继续开发，把本文件补全后移动到 `active/`，再调用 `spec_context`。",
    "",
    "## 待确认问题",
    "",
    "- 这个模块对应的真实业务名称是什么？",
    "- 当前可观察行为中哪些必须保持，哪些可以调整？",
    "- 是否存在未在测试中覆盖的权限、状态、并发、幂等或错误处理规则？",
    "- 默认参数、配置来源和环境差异是否明确？",
    "",
    "## 总结模板",
    "",
    "- 业务目标：AI 阅读源码后填写。",
    "- 关键入口：列出已阅读的文件、函数、路由、组件或测试。",
    "- 功能全过程：描述触发入口、输入与前置状态、执行步骤、输出结果和副作用。",
    "- 未确认规则：列出必须向用户确认的问题。",
    "",
    "## 行为约定",
    "",
    "| 场景 | 条件 | 当前源码行为 | 目标行为 | 证据文件 |",
    "|---|---|---|---|",
    "| 正常 | AI 阅读源码后填写 | AI 阅读源码后填写 | 待用户确认 | 待读取 |",
    "| 失败 | AI 阅读源码后填写 | AI 阅读源码后填写 | 待用户确认 | 待读取 |",
    "| 边界 | AI 阅读源码后填写 | AI 阅读源码后填写 | 待用户确认 | 待读取 |",
    "",
    "## 执行记录",
    "",
    "- 记录来源：只能记录已阅读代码、测试结果或用户确认的事实。",
    "- 功能全过程：AI 阅读源码后按功能点补充触发入口、输入来源、执行步骤、输出结果和副作用。",
    "- 分支条件：AI 阅读源码后补充真实正常、失败、边界、权限和状态分支，不只写摘要。",
    "- 默认参数行为：AI 阅读源码后补充默认值、配置来源、覆盖规则以及未传参数时的完整流程。",
    "- 边界处理结果：AI 阅读源码后补充异常、空值、权限、状态等输入如何进入分支、在哪里返回、是否产生副作用。",
    "- 验证结果：AI 运行或确认验证命令后记录覆盖的流程分支。",
    "- 禁止事项：不要把静态线索、猜测或“看起来合理”的行为写成事实。",
    "",
    "## 完成标准",
    "",
    "- AI 已阅读相关源码和测试，而不是只依据本文件的静态线索。",
    "- 行为约定、功能全过程、默认参数、边界处理和风险问题已用中文补全。",
    "- 若本 spec 仅用于审查且不需要改动，可保持 `source-review/needs-ai-summary` 状态。",
    "- 若当前功能需要移除，把状态改为 `active/removal` 并写清移除范围。"
  ]);
}
