/* User-authored spec templates and source-derived review spec templates. */
import { businessConfirmationSection, list, workflowGuardSection, engineeringConstraintSection } from "./markdown.js";
import type { SourceScanSummary, SourceSpecCandidate } from "../spec/types.js";

export function specTemplate(kind: "feature" | "bugfix" | "removal"): string {
  const title = kind === "feature" ? "新增功能" : kind === "bugfix" ? "问题修复" : "移除功能";
  return [
    `# ${title}`,
    "",
    "## Meta",
    "",
    "- status: draft",
    "- source: user-authored",
    "",
    "## 目标",
    "",
    "- 待描述。",
    "",
    "## 影响范围",
    "",
    "- 后端/API：待确认",
    "- 前端/客户端：待确认",
    "- 数据/迁移：待确认",
    "- 测试：待确认",
    "",
    "## 行为规则",
    "",
    "| 场景 | 条件 | 预期结果 |",
    "|---|---|---|",
    "| 正常 | 待补充 | 待补充 |",
    "| 失败 | 待补充 | 待补充 |",
    "",
    "## AI 实现计划",
    "",
    "- 改动范围：待补充。",
    "- 关键文件：待补充。",
    "- 数据流：待补充。",
    "- 分支处理：列出正常、失败、边界和异常分支。",
    "- 默认值/配置：列出默认参数、配置来源和覆盖规则。",
    "- 风险确认：不明确或高影响规则先向用户确认。",
    "",
    "## 实际行为记录",
    "",
    "- 分支条件：完成后补充已实现行为。",
    "- 默认参数行为：完成后补充默认值和覆盖规则。",
    "- 边界处理结果：完成后补充异常、空值、权限、状态等处理结果。",
    "- 验证结果：完成后记录验证命令和结果。",
    "",
    "## 验收标准",
    "",
    "- 待补充可验证结果。",
    "",
    ...workflowGuardSection(),
    "",
    ...engineeringConstraintSection(),
    "",
    ...businessConfirmationSection(),
    "",
    "## TODO",
    "",
    "- [ ] 按本 spec 定位相关代码。",
    "- [ ] 更新实现和测试。",
    "- [ ] 运行验证并记录结果。",
    "",
    "## 代码线索",
    "",
    "- 待补充相关文件、函数、路由、组件或测试。"
  ].join("\n");
}

export function sourceInventory(summary: SourceScanSummary, generatedAt: string): string {
  const section = (title: string, items: string[]) => [`## ${title}`, "", ...list(items), ""].join("\n");
  return [
    "# 源码审查线索清单",
    "",
    `生成时间：${generatedAt}`,
    "",
    `扫描源码和配置文件 ${summary.totalFiles} 个。以下只是静态启发式线索，用于帮助 AI 选择阅读入口，不代表业务事实或最终 spec。`,
    "",
    section("Manifest", summary.manifests),
    section("API 文件", summary.apiFiles),
    section("UI 文件", summary.uiFiles),
    section("数据文件", summary.dataFiles),
    section("测试文件", summary.testFiles),
    section("路由线索", summary.routeHints),
    section("组件线索", summary.componentHints),
    section("模型线索", summary.modelHints)
  ].join("\n");
}

export function reviewIndex(specsDir: string, candidates: SourceSpecCandidate[]): string {
  return [
    "# AI 源码审查任务索引",
    "",
    "| Spec | 文件 | 状态 | 来源 |",
    "|---|---|---|---|",
    ...(candidates.length
      ? candidates.map((item) => `| ${item.title} | \`${specsDir}/review/${item.domain}-${item.name}.md\` | source-review/needs-ai-summary | 静态线索，待 AI 阅读源码 |`)
      : ["| 待补充 | 待补充 | 待审查 | 静态线索，待 AI 阅读源码 |"])
  ].join("\n");
}

export function sourceReviewSpec(projectName: string, input: SourceSpecCandidate): string {
  return [
    `# ${input.title}`,
    "",
    "## Meta",
    "",
    "- status: source-review/needs-ai-summary",
    "- source: static-source-hints",
    "- review: required",
    "",
    "## 使用边界",
    "",
    `本文件由 MCP 基于 \`${projectName}\` 的源码路径、命名、路由、导出和测试线索生成。它不是业务结论，只是交给 AI 阅读源码的任务单。`,
    "",
    "- 禁止把下面的静态线索当成业务事实。",
    "- AI 必须打开并阅读相关源码、测试和配置后，再填写业务目标、行为规则和验收标准。",
    "- 金额、状态机、并发、权限等规则来源不明时，必须向用户确认。",
    "",
    "## 优先阅读入口",
    "",
    ...list(input.evidence),
    "",
    "## 路由/接口搜索线索",
    "",
    ...list(input.routes, "未识别到明显路由"),
    "",
    "## UI/客户端搜索线索",
    "",
    ...list(input.components, "未识别到明显组件"),
    "",
    "## 数据模型搜索线索",
    "",
    ...list(input.models, "未识别到明显模型"),
    "",
    "## 测试搜索线索",
    "",
    ...list(input.tests, "未识别到相关测试"),
    "",
    "## AI 阅读任务",
    "",
    "- 读取优先入口、相关导入导出、调用方和测试，确认真实业务目标。",
    "- 总结正常流程、失败分支、默认参数、边界条件、权限和数据约束。",
    "- 标明哪些行为来自源码证据，哪些规则仍需用户确认。",
    "- 若要继续开发，把本文件补全后移动到 `active/`，再调用 `spec_context`。",
    "",
    "## 待确认问题",
    "",
    "- 这个模块对应的真实业务名称是什么？",
    "- 当前可观察行为中哪些必须保持，哪些可以调整？",
    "- 是否存在未在测试中覆盖的权限、状态、并发、幂等或错误处理规则？",
    "- 默认参数、配置来源和环境差异是否明确？",
    "",
    "## AI 总结输出模板",
    "",
    "- 业务目标：AI 阅读源码后填写。",
    "- 关键入口：列出已阅读的文件、函数、路由、组件或测试。",
    "- 数据流：描述输入、处理、输出和副作用。",
    "- 未确认规则：列出必须向用户确认的问题。",
    "",
    "## 行为规则",
    "",
    "| 场景 | 条件 | 当前源码行为 | 目标行为 | 证据文件 |",
    "|---|---|---|---|",
    "| 正常 | AI 阅读源码后填写 | AI 阅读源码后填写 | 待用户确认 | 待读取 |",
    "| 失败 | AI 阅读源码后填写 | AI 阅读源码后填写 | 待用户确认 | 待读取 |",
    "| 边界 | AI 阅读源码后填写 | AI 阅读源码后填写 | 待用户确认 | 待读取 |",
    "",
    "## 实际行为记录",
    "",
    "- 分支条件：AI 阅读源码后补充真实分支。",
    "- 默认参数行为：AI 阅读源码后补充默认值、配置来源和覆盖规则。",
    "- 边界处理结果：AI 阅读源码后补充异常、空值、权限、状态等处理结果。",
    "- 验证结果：AI 运行或确认验证命令后记录。",
    "",
    "## 验收标准",
    "",
    "- AI 已阅读相关源码和测试，而不是只依据本文件的静态线索。",
    "- 行为规则、默认参数、边界处理和风险问题已用中文补全。",
    "- 若本 spec 仅用于审查且不需要改动，可保持 `source-review/needs-ai-summary` 状态。",
    "- 若当前功能需要移除，把状态改为 `active/removal` 并写清移除范围。"
  ].join("\n");
}
